### ISSUE TITLE
MVPレビューの前に

### ISSUE THREAD

**Issue by Tsuchiya2** [Yamamoto-Masaya1122/train_window_trip#79]
MVPレビューの前に確認したいことを以下に記載しますのでご回答をお願いいたします。

---

https://github.com/Yamamoto-Masaya1122/train_window_trip/pull/1

上記のREADMEレビューに通過した際、「レコメンド機能」があったかと思いますが、公開されているサービスでどこを触れれば、それが確認できるかをお聞きしたいです。

取り急ぎご指摘いただければ、対応時間中に確認いたしますので、ご返答よろしくお願いいたします。

**Comment by Yamamoto-Masaya1122** [comment]
お忙しい中、コメントをいただきありがとうございます。

> https://github.com/Yamamoto-Masaya1122/train_window_trip/pull/1

上記のREADMEレビューに通過した際、「レコメンド機能」があったかと思いますが、公開されているサービスでどこを触れれば、それが確認できるかをお聞きしたいです。

こちらの件に関しましては、レコメンド機能を実装する段階になった際に自分の技術力が足りず、実装のイメージが湧かなかったため、機能の追加を諦めて代わりに路線詳細機能を実装することにしました。
https://github.com/Yamamoto-Masaya1122/train_window_trip/pull/75

**Comment by Tsuchiya2** [comment]
なるほど。。READMEレビュー後に変更をされたということですね。

MVPレビューはREADMEレビュー時のREADMEを元に行う形を取っています。
そのため変更後の内容がREADMEレビューを通るかどうかをレビューする必要が生じてきます。

お手数ですがMVPレビューの前に、先程のMattermostに改めてREADME変更のプルリクエストを作成の上、講師にレビューをしてもらうようにお願いいたします。

**Comment by Yamamoto-Masaya1122** [comment]
申し訳ございません！そうとは知らず勝手にREADMEを修正して、実装を進めてしまいました。
改めてREADME変更のプルリクエストを作成し、Mattermostでレビューを依頼させていただきます！
