### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [Yamamoto-Masaya1122/train_window_trip#94]
@Yamamoto-Masaya1122 
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
各路線の動画も見れる&情報も集まっていますね！

## 静的コードチェックが入っている
rubocop導入してしっかりチェックしていますね！

## 就活において十分な技術力を示せる機能を実装しているか
ActionCableの実装などいいですね。
もうひとつほど強めに技術をアピールできるポイントがあるとよさそうです。
ランキング機能などもいいですが、季節ごとで言ってほしい路線などもあると思うので、ユーザーのお気に入り以外でのおすすめランキング機能があるといいですね！（データを用いたロジックを作るので技術的にもプラスアルファになります）

下記に気になった点を挙げておいたので、ご確認ください。

- youtube_searchs_controllerのyoutubeAPiの処理はserviceクラスなどに処理を切り出して、controllerではそれを利用するようにしましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記に気になった点を挙げておいたので、ご確認ください。

- 路線検索時に、検索した情報が検索フォームに残っていないので残すようにしましょう。
- チャットルームの意味合いが弱いかなと思うので、複数人で旅行する場合のチャットルーム的な位置付けにしてあげると、リアルタイムチャットの意味合いも強くなるので、見せ方を変えてみましょう。
- ちょっとマイページが簡易的なので、本リリースまでにはUIをよくしておきましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by kerochelo** [comment]
@Yamamoto-Masaya1122 
> 大変申し訳ないのですが、チャットルームの意味合いが弱いというのがなかなかイメージが湧かないです。今の見せ方だと、
リアルタイム通信でやり取りする必要はなくない？と見られるということでしょうか？
具体的にどういうことかを教えていただけると幸いです。

そうですね。
技術のアピールポイントとしてはとてもいいのですが、コメント的な意味合いの部分なので、リアルタイムにしなくてもよさそうと思われるかもしれないです。
ActionCableを使ってリアルタイムのチャットのやり取りが必要になる場面的にはただのコメントのやり取りというよりかは、同じ状況に一緒にいて、そこでみんなでやり取りする方が自然かなといったところです。
そのため最初からチャットルームがあるわけではなく、チャットルームを作る動作があってそれからリアルタイムチャットでみんなで楽しむなどの導線が自然になるかなといったところです。（それをログ的にしてチャット記録を後から見れるようにするなどで思い出を残すような形にするのもよさそうかなと！）

**Comment by Yamamoto-Masaya1122** [comment]
コメントしていただきありがとうございます！

同じ状況に一緒にいて、そこでみんなでやり取りする方が自然だということは、おっしゃる通りだと思いました！
各路線でユーザーがチャットルームを作ることができて、そこでユーザー同士が自由にコミュニケーションができるみたいな感じだと良さそうですね！（2ちゃんねるのスレのようなイメージ？ https://2chmm.com/）

**Comment by Yamamoto-Masaya1122** [comment]
コメントいただきありがとうございます。

確かにリアルタイムのチャットのやり取りが必要になるのは、同じ状況に一緒にいて、そこでみんなでやり取りする方が自然だということはおっしゃる通りだと思いました！
僕の中では、
- 各路線に対して、ユーザーはチャットルームを作ることができる。
- チャットルーム内で他のユーザーとコミュニケーションを取ることができる。
という感じで、[2chの掲示板のスレ](https://2chmm.com/)のようなイメージなのですが

**Comment by kerochelo** [comment]
@Yamamoto-Masaya1122 
いいですね！
そのイメージでチャット機能を修正タスクも作っておきましょう！
（時間かかると思うので、タスク分解して時間の許す限りの実装をしていきましょう）

**Comment by Yamamoto-Masaya1122** [comment]
@kerochelo 
ありがとうございます！！

テーブル同士の関係を考え直さないといけないので、結構時間かかりそうです。。

アドバイスをいただいた箇所もissueに落とし込んだのでご確認よろしくお願いいたします！
あと、本リリースは10月31日に変更しました。

**Comment by kerochelo** [comment]
@Yamamoto-Masaya1122 
確認しました、引き続き頑張っていきましょ！

**Comment by Yamamoto-Masaya1122** [comment]
@kerochelo 
ありがとうございます！頑張ります！
